# SPDX-FileCopyrightText: 2026 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0
"""Add rooms table and booking.room_id FK.

Revision ID: 0eeb46d10f64
Revises: fe3f58f8fb26
Create Date: 2026-02-01 19:29:52.470493+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0eeb46d10f64"
down_revision: str | None = "fe3f58f8fb26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("cloudbeds_room_id", sa.String(length=100), nullable=False),
        sa.Column("room_name", sa.String(length=255), nullable=False),
        sa.Column("room_type_name", sa.String(length=255), nullable=True),
        sa.Column("ical_url_slug", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_id", "cloudbeds_room_id", name="uq_room_listing_cloudbeds"
        ),
        sa.UniqueConstraint("listing_id", "ical_url_slug", name="uq_room_listing_slug"),
    )
    op.create_index("idx_room_enabled", "rooms", ["enabled"], unique=False)
    op.create_index("idx_room_listing", "rooms", ["listing_id"], unique=False)

    # Use batch mode for SQLite compatibility when adding FK to existing table
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("room_id", sa.Integer(), nullable=True))
        batch_op.create_index("idx_booking_room", ["room_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_booking_room_id", "rooms", ["room_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_constraint("fk_booking_room_id", type_="foreignkey")
        batch_op.drop_index("idx_booking_room")
        batch_op.drop_column("room_id")

    op.drop_index("idx_room_listing", table_name="rooms")
    op.drop_index("idx_room_enabled", table_name="rooms")
    op.drop_table("rooms")
    # ### end Alembic commands ###
