# SPDX-FileCopyrightText: 2026 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0
"""Initial schema.

Revision ID: 0dcd97f41bbd
Revises:
Create Date: 2026-01-30 21:21:23.852823+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "0dcd97f41bbd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cloudbeds_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("ical_url_slug", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("last_sync_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_listing_enabled", "listings", ["enabled"], unique=False)
    op.create_index(
        op.f("ix_listings_cloudbeds_id"), "listings", ["cloudbeds_id"], unique=True
    )
    op.create_index(
        op.f("ix_listings_ical_url_slug"), "listings", ["ical_url_slug"], unique=True
    )
    op.create_table(
        "oauth_credentials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("cloudbeds_booking_id", sa.String(length=100), nullable=False),
        sa.Column("guest_name", sa.String(length=255), nullable=True),
        sa.Column("guest_phone_last4", sa.String(length=4), nullable=True),
        sa.Column("check_in_date", sa.DateTime(), nullable=False),
        sa.Column("check_out_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("custom_data", sqlite.JSON(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_id", "cloudbeds_booking_id", name="uq_booking_listing_cloudbeds"
        ),
    )
    op.create_index(
        "idx_booking_dates",
        "bookings",
        ["listing_id", "check_in_date", "check_out_date"],
        unique=False,
    )
    op.create_index("idx_booking_listing", "bookings", ["listing_id"], unique=False)
    op.create_index("idx_booking_status", "bookings", ["status"], unique=False)
    op.create_table(
        "custom_fields",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("display_label", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_id", "field_name", name="uq_customfield_listing_field"
        ),
    )
    op.create_index(
        "idx_customfield_listing", "custom_fields", ["listing_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_customfield_listing", table_name="custom_fields")
    op.drop_table("custom_fields")
    op.drop_index("idx_booking_status", table_name="bookings")
    op.drop_index("idx_booking_listing", table_name="bookings")
    op.drop_index("idx_booking_dates", table_name="bookings")
    op.drop_table("bookings")
    op.drop_table("oauth_credentials")
    op.drop_index(op.f("ix_listings_ical_url_slug"), table_name="listings")
    op.drop_index(op.f("ix_listings_cloudbeds_id"), table_name="listings")
    op.drop_index("idx_listing_enabled", table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
