# SPDX-FileCopyrightText: 2026 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0
"""Add api_key column to oauth_credentials.

Revision ID: fe3f58f8fb26
Revises: 0dcd97f41bbd
Create Date: 2026-01-31 17:48:08.765418+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe3f58f8fb26"
down_revision: str | None = "0dcd97f41bbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth_credentials", sa.Column("api_key", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_credentials", "api_key")
    # ### end Alembic commands ###
